site_name: DD2414 RPL Autum 2020
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
theme:
  name: material
  logo: img/drone.png
  icon:
    repo: fontawesome/brands/github
  palette:
    # Toggle mode
    - scheme: slate
      primary: white
      accent: deep orange
repo_url: https://github.com/alsarmie/KTH-CAS-UAV-DD2414.git
repo_name: DD2414-PX4-11.2.0

nav:
    - Home: index.md
    - About: about.md
    - User Guide:
      # Assembly
      - 'Build a drone.': guide/build_hardware.md
      # Software setup
      - 'Install the software.': guide/install_software.md
      - 'Calibrate steering and throttle.': guide/calibrate.md
      - 'Get flying.': guide/get_driving.md
    - Assembly:
      - 'About': assembly/about.md
      - 'Frame': assembly/frame.md
      - 'Landing Gear': assembly/landing_gear.md
      - 'Sensor Plate': assembly/sensor_plate.md

    - Design:
      - 'Mechanical design': design/mechanical.md
      - 'Electrical design': design/electrical.md
      - 'Flight time considerations': design/flight_considerations.md
    - Parts:
      - 'Summary': parts/about.md
      - 'Purchased Parts': parts/purchased_parts.md
      - 'Printed Parts': parts/printed_parts.md
      - 'Cabling': parts/cabling.md
      - 'Hardware / Fasteners': parts/hardware.md

    - Future Work: future_work.md
    - Weekly Updates & Tests: tests.md
