site_name: DD2414 RPL Autum 2020

theme:
  name: material
  logo: img/drone.png
  icon:
    repo: fontawesome/brands/github
  palette:
    # Toggle mode
    - scheme: slate
      primary: white
      accent: deep orange
repo_url: https://github.com/alsarmie/KTH-CAS-UAV-DD2414.git
repo_name: DD2414-PX4-11.2.0

nav:
    - Home: index.md
    - About: about.md
    - User Guide:
      - 'Build a drone.': guide/build_hardware.md
      - 'Install the software.': guide/install_software.md
      - 'Calibrate steering and throttle.': guide/calibrate.md
      - 'Get flying.': guide/get_driving.md
    - Parts:
      - 'Summary': parts/about.md
      - 'Purchased Parts': parts/purchased_parts.md
      - 'Printed Parts': parts/printed_parts.md
      - 'Cabling': parts/cabling.md
      - 'Hardware / Fasteners': parts/hardware.md

    - Contribute: contribute.md
    - Tests: tests.md
    - FAQ: faq.md
