site_name: DD2414 RPL Autum 2020
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
theme:
  name: material
  logo: img/drone.png
  icon:
    repo: fontawesome/brands/github
  palette:
    # Toggle mode
    - scheme: slate
      primary: white
      accent: deep orange
repo_url: https://github.com/alsarm/PX4-Autopilot.git
repo_name: DD2414-PX4-11.2.0

nav:
    - Home: index.md

    - About: about.md

    - Assembly:
      - 'About': assembly/about.md
      - 'Frame': assembly/frame.md
      - 'Propulsion': assembly/propulsion.md
      - 'Landing Gear': assembly/landing_gear.md
      - 'Sensor Plate': assembly/sensor_plate.md
      - 'Peripherals': assembly/peripherals.md

    - Design:
      - 'Mechanical design': design/mechanical.md
      - 'Electrical design': design/electrical.md
      - 'Flight time considerations': design/flight_considerations.md

    - Parts:
      - 'Summary': parts/summary.md
      - 'Purchased Parts': parts/purchased_parts.md
      - 'Printed Parts': parts/printed_parts.md
      - 'Cabling': parts/cabling.md
      - 'Fasteners': parts/fasteners.md

    - Setup:
      - 'Install the software.': setup/install_software.md
      - 'Radio': setup/radio_setup.md
      - 'Flight Modes': setup/flight_modes.md
      - 'MAVROS': setup/mavros_setup.md
      - 'MoCap System': setup/mocap_setup.md

    - Flying:
      - 'Flight Safety': flying/flight_safety.md
      - 'Flight Procedure': flying/flight_procedure.md
      - 'Flight Reporting': flying/flight_reporting.md

    - Future Work: future_work.md

    - Weekly Updates & Tests: tests.md
